### ISSUE TITLE
Checklist to finish by Monday 04/29

### ISSUE THREAD

**Issue by timashana** [ncp-hash/public-phash#11]
- [x] **Ana**. Finish ZKP:
  * Either figure out how to assign mpz_t to paillier_ciphertext_t OR
  * Overload mult_and_sum to work only with mpz_t and not paillier_ciphertext_t (do the computation in the clear mod N^2)

- [x] **David:**. Finish IPC by Monday.
  * Otherwise, we will ask Professor WES for help.

- [x] **Bon:**. Add Scheme 2 in the clear and run it on two similar images - see if it's producing similar hashes for some transformations.
  * If not, go back to mean block hash we implemented before and see which transformations produce similar hashes vs different ones

**Comment by timashana** [comment]
Gave Rosario the update and TCP block, closing issue

**Comment by timashana** [comment]
David will continue working with WES on TCP
